---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  container:
    runs-on: ubuntu-latest
    container: sweisz/book-latex-container:1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo This job does specify a container.
          cd book; make
        name: Run in container
      - name: Push pdf
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.ACCESS_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            book/uso.pdf
